development:
  adapter: postgresql
  database: eli5_development
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: eli5_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: eli5_production
  pool: 5
  timeout: 5000
